//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidzaniaService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KidzaniaService.TicketBookSoap")]
    public interface TicketBookSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_City", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.City_Out[]> FnSchedule_CityAsync(long CityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Park", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Park_Out[]> FnSchedule_ParkAsync(long CityId, long ParkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Park_Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Park_Out[]> FnSchedule_Park_SyncAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Shift", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Shift_Out[]> FnSchedule_ShiftAsync(long CityId, long ParkId, System.DateTime Visit_Date, string PartnerId, string PartnerPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Visitors_Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> FnSchedule_Visitors_SyncAsync(long ParkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Shift_Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> FnSchedule_Shift_SyncAsync(long ParkId, System.DateTime Visit_From, System.DateTime Visit_To);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Sexes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Sexes_Out[]> FnSchedule_SexesAsync(long ParkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_VisitDate_Park", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vd_Park_Out[]> FnSchedule_VisitDate_ParkAsync(long ParkId, System.DateTime Visit_Date, string PartnerId, string PartnerPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_VisitDate_City", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vd_Park_Out[]> FnSchedule_VisitDate_CityAsync(long CityId, System.DateTime Visit_Date, string PartnerId, string PartnerPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CancelBookAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Book", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Book_Out> BookAsync(
                    long ParkId, 
                    long ShiftId, 
                    System.DateTime Visit_Date, 
                    long NoOfTickets, 
                    long VisitorId1, 
                    string VisitorTypeDesc1, 
                    string VisitorName1, 
                    string VisitorSex1, 
                    long VisitorAge1, 
                    long VisitorId2, 
                    string VisitorTypeDesc2, 
                    string VisitorName2, 
                    string VisitorSex2, 
                    long VisitorAge2, 
                    long VisitorId3, 
                    string VisitorTypeDesc3, 
                    string VisitorName3, 
                    string VisitorSex3, 
                    long VisitorAge3, 
                    long VisitorId4, 
                    string VisitorTypeDesc4, 
                    string VisitorName4, 
                    string VisitorSex4, 
                    long VisitorAge4, 
                    long VisitorId5, 
                    string VisitorTypeDesc5, 
                    string VisitorName5, 
                    string VisitorSex5, 
                    long VisitorAge5, 
                    long VisitorId6, 
                    string VisitorTypeDesc6, 
                    string VisitorName6, 
                    string VisitorSex6, 
                    long VisitorAge6, 
                    long VisitorId7, 
                    string VisitorTypeDesc7, 
                    string VisitorName7, 
                    string VisitorSex7, 
                    long VisitorAge7, 
                    long VisitorId8, 
                    string VisitorTypeDesc8, 
                    string VisitorName8, 
                    string VisitorSex8, 
                    long VisitorAge8, 
                    long VisitorId9, 
                    string VisitorTypeDesc9, 
                    string VisitorName9, 
                    string VisitorSex9, 
                    long VisitorAge9, 
                    long VisitorId10, 
                    string VisitorTypeDesc10, 
                    string VisitorName10, 
                    string VisitorSex10, 
                    long VisitorAge10, 
                    string PartnerId, 
                    string PartnerPwd, 
                    long UniqueRequestId, 
                    string CustomerIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Vouchers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> VouchersAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AvailableVouchers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.AvailableVouchers_Out> AvailableVouchersAsync(string PartnerId, string PartnerPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UseVoucher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.UseVoucher_Out> UseVoucherAsync(
                    long ParkId, 
                    string PartnerId, 
                    string PartnerPwd, 
                    long UniqueRequestId, 
                    string BinNo, 
                    string CardName, 
                    int BookletId, 
                    long BookletNo, 
                    int VouId1, 
                    string VouNo1, 
                    string AddnlSecValidOnValue1, 
                    int VouId2, 
                    string VouNo2, 
                    string AddnlSecValidOnValue2, 
                    int VouId3, 
                    string VouNo3, 
                    string AddnlSecValidOnValue3, 
                    int VouId4, 
                    string VouNo4, 
                    string AddnlSecValidOnValue4, 
                    int VouId5, 
                    string VouNo5, 
                    string AddnlSecValidOnValue5, 
                    int VouId6, 
                    string VouNo6, 
                    string AddnlSecValidOnValue6, 
                    int VouId7, 
                    string VouNo7, 
                    string AddnlSecValidOnValue7, 
                    int VouId8, 
                    string VouNo8, 
                    string AddnlSecValidOnValue8, 
                    int VouId9, 
                    string VouNo9, 
                    string AddnlSecValidOnValue9, 
                    int VouId10, 
                    string VouNo10, 
                    string AddnlSecValidOnValue10, 
                    bool RepeatCall);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoVouchers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> AutoVouchersAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UseAutoVoucher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.UseVoucher_Out> UseAutoVoucherAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UseVoucherRollback", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.UseVoucher_Out> UseVoucherRollbackAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, bool IsRollbackAll, int VouId, string VouNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Buy_Out> BuyAsync(
                    long ParkId, 
                    string PartnerId, 
                    string PartnerPwd, 
                    long UniqueRequestId, 
                    string PayType, 
                    string PayConfNo, 
                    string Remarks, 
                    string MobileNo, 
                    System.DateTime Visit_Date, 
                    long Shift_Id, 
                    string OrderId, 
                    string OrderRef, 
                    string MTR, 
                    string TransactionId, 
                    string RRN, 
                    string PayAuthId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FnSchedule_Discount_Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> FnSchedule_Discount_SyncAsync(long ParkId, System.DateTime Visit_From, System.DateTime Visit_To);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueVouchers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> IssueVouchersAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueVoucherValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> IssueVoucherValidateAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId, int IssueQty, string BinNo, string CardNo, string MobileNo, string EmailId, string UniqueCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueVoucherBook", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.IssueVouchers_Out> IssueVoucherBookAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId, int IssueQty, string BinNo, string CardNo, string MobileNo, string EmailId, string UniqueCode, string NameOnCard);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueVoucherCancel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> IssueVoucherCancelAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IssueVoucherMark", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<KidzaniaService.IssueVouchers_Out> IssueVoucherMarkAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId, int IssueQty, string BinNo, string CardNo, string MobileNo, string EmailId, string UniqueCode, string NameOnCard, string[] VouNos);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class City_Out
    {
        
        private long cityIdField;
        
        private string cityNameField;
        
        private int errIdField;
        
        private string errorStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CityId
        {
            get
            {
                return this.cityIdField;
            }
            set
            {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ErrId
        {
            get
            {
                return this.errIdField;
            }
            set
            {
                this.errIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorString
        {
            get
            {
                return this.errorStringField;
            }
            set
            {
                this.errorStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IssueVouchers_Out
    {
        
        private long parkIdField;
        
        private long uniqueRequestIdField;
        
        private string partnerIdField;
        
        private int statusIdField;
        
        private string errMessageField;
        
        private KidzaniaService.ArrayOfXElement vouchersField;
        
        private string[] issueVouherNosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UniqueRequestId
        {
            get
            {
                return this.uniqueRequestIdField;
            }
            set
            {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrMessage
        {
            get
            {
                return this.errMessageField;
            }
            set
            {
                this.errMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public KidzaniaService.ArrayOfXElement Vouchers
        {
            get
            {
                return this.vouchersField;
            }
            set
            {
                this.vouchersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] IssueVouherNos
        {
            get
            {
                return this.issueVouherNosField;
            }
            set
            {
                this.issueVouherNosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Buy_Out
    {
        
        private long parkIdField;
        
        private long uniqueRequestIdField;
        
        private string partnerIdField;
        
        private int statusIdField;
        
        private string errMessageField;
        
        private string payTypeField;
        
        private string payConfNoField;
        
        private long receiptNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UniqueRequestId
        {
            get
            {
                return this.uniqueRequestIdField;
            }
            set
            {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrMessage
        {
            get
            {
                return this.errMessageField;
            }
            set
            {
                this.errMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PayType
        {
            get
            {
                return this.payTypeField;
            }
            set
            {
                this.payTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PayConfNo
        {
            get
            {
                return this.payConfNoField;
            }
            set
            {
                this.payConfNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long ReceiptNo
        {
            get
            {
                return this.receiptNoField;
            }
            set
            {
                this.receiptNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UseVoucher_Out
    {
        
        private long parkIdField;
        
        private long uniqueRequestIdField;
        
        private string partnerIdField;
        
        private int statusIdField;
        
        private string errMessageField;
        
        private KidzaniaService.ArrayOfXElement voucherUseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UniqueRequestId
        {
            get
            {
                return this.uniqueRequestIdField;
            }
            set
            {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrMessage
        {
            get
            {
                return this.errMessageField;
            }
            set
            {
                this.errMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public KidzaniaService.ArrayOfXElement VoucherUseStatus
        {
            get
            {
                return this.voucherUseStatusField;
            }
            set
            {
                this.voucherUseStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AvailableVouchers_Out
    {
        
        private long parkIdField;
        
        private long uniqueRequestIdField;
        
        private string partnerIdField;
        
        private int statusIdField;
        
        private string errMessageField;
        
        private KidzaniaService.ArrayOfXElement vouchersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UniqueRequestId
        {
            get
            {
                return this.uniqueRequestIdField;
            }
            set
            {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrMessage
        {
            get
            {
                return this.errMessageField;
            }
            set
            {
                this.errMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public KidzaniaService.ArrayOfXElement Vouchers
        {
            get
            {
                return this.vouchersField;
            }
            set
            {
                this.vouchersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vouchers_Out
    {
        
        private long parkIdField;
        
        private long uniqueRequestIdField;
        
        private string partnerIdField;
        
        private int statusIdField;
        
        private string errMessageField;
        
        private KidzaniaService.ArrayOfXElement vouchersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long UniqueRequestId
        {
            get
            {
                return this.uniqueRequestIdField;
            }
            set
            {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrMessage
        {
            get
            {
                return this.errMessageField;
            }
            set
            {
                this.errMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public KidzaniaService.ArrayOfXElement Vouchers
        {
            get
            {
                return this.vouchersField;
            }
            set
            {
                this.vouchersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ticket
    {
        
        private string ticketNumberField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TicketNumber
        {
            get
            {
                return this.ticketNumberField;
            }
            set
            {
                this.ticketNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Book_Out
    {
        
        private long parkIdField;
        
        private int shiftIdField;
        
        private int noOfTicketsField;
        
        private long uniqueRequestIdField;
        
        private string partnerIdField;
        
        private int statusIdField;
        
        private string errMessageField;
        
        private string saleNumberField;
        
        private Ticket[] ticketsField;
        
        private double chargeField;
        
        private double otherChargeField;
        
        private double serviceChargeField;
        
        private double totalChargeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ShiftId
        {
            get
            {
                return this.shiftIdField;
            }
            set
            {
                this.shiftIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NoOfTickets
        {
            get
            {
                return this.noOfTicketsField;
            }
            set
            {
                this.noOfTicketsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long UniqueRequestId
        {
            get
            {
                return this.uniqueRequestIdField;
            }
            set
            {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PartnerId
        {
            get
            {
                return this.partnerIdField;
            }
            set
            {
                this.partnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrMessage
        {
            get
            {
                return this.errMessageField;
            }
            set
            {
                this.errMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SaleNumber
        {
            get
            {
                return this.saleNumberField;
            }
            set
            {
                this.saleNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public Ticket[] Tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double Charge
        {
            get
            {
                return this.chargeField;
            }
            set
            {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double OtherCharge
        {
            get
            {
                return this.otherChargeField;
            }
            set
            {
                this.otherChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double ServiceCharge
        {
            get
            {
                return this.serviceChargeField;
            }
            set
            {
                this.serviceChargeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double TotalCharge
        {
            get
            {
                return this.totalChargeField;
            }
            set
            {
                this.totalChargeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VisitorTypes
    {
        
        private long visitorTypeIdField;
        
        private string visitorTypeDescField;
        
        private long visitorMinAgeField;
        
        private long visitorMaxAgeField;
        
        private long visitorTypeAliasIdField;
        
        private long priceIdField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long VisitorTypeId
        {
            get
            {
                return this.visitorTypeIdField;
            }
            set
            {
                this.visitorTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string VisitorTypeDesc
        {
            get
            {
                return this.visitorTypeDescField;
            }
            set
            {
                this.visitorTypeDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long VisitorMinAge
        {
            get
            {
                return this.visitorMinAgeField;
            }
            set
            {
                this.visitorMinAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long VisitorMaxAge
        {
            get
            {
                return this.visitorMaxAgeField;
            }
            set
            {
                this.visitorMaxAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long VisitorTypeAliasId
        {
            get
            {
                return this.visitorTypeAliasIdField;
            }
            set
            {
                this.visitorTypeAliasIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long PriceId
        {
            get
            {
                return this.priceIdField;
            }
            set
            {
                this.priceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vd_Park_Out
    {
        
        private long cityIdField;
        
        private long parkIdField;
        
        private long shiftIdField;
        
        private VisitorTypes[] visitorTypesField;
        
        private int errIdField;
        
        private string errorStringField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CityId
        {
            get
            {
                return this.cityIdField;
            }
            set
            {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long ShiftId
        {
            get
            {
                return this.shiftIdField;
            }
            set
            {
                this.shiftIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public VisitorTypes[] VisitorTypes
        {
            get
            {
                return this.visitorTypesField;
            }
            set
            {
                this.visitorTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ErrId
        {
            get
            {
                return this.errIdField;
            }
            set
            {
                this.errIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorString
        {
            get
            {
                return this.errorStringField;
            }
            set
            {
                this.errorStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sexes_Out
    {
        
        private long parkIdField;
        
        private string parkNameField;
        
        private string descriptionField;
        
        private string initialField;
        
        private int errIdField;
        
        private string errorStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ParkName
        {
            get
            {
                return this.parkNameField;
            }
            set
            {
                this.parkNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Initial
        {
            get
            {
                return this.initialField;
            }
            set
            {
                this.initialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ErrId
        {
            get
            {
                return this.errIdField;
            }
            set
            {
                this.errIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorString
        {
            get
            {
                return this.errorStringField;
            }
            set
            {
                this.errorStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Shift_Out
    {
        
        private long cityIdField;
        
        private long parkIdField;
        
        private string parkNameField;
        
        private long shiftIdField;
        
        private string shiftNameField;
        
        private string startOurField;
        
        private string endOurField;
        
        private int errIdField;
        
        private string errorStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CityId
        {
            get
            {
                return this.cityIdField;
            }
            set
            {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ParkName
        {
            get
            {
                return this.parkNameField;
            }
            set
            {
                this.parkNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long ShiftId
        {
            get
            {
                return this.shiftIdField;
            }
            set
            {
                this.shiftIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ShiftName
        {
            get
            {
                return this.shiftNameField;
            }
            set
            {
                this.shiftNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StartOur
        {
            get
            {
                return this.startOurField;
            }
            set
            {
                this.startOurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string EndOur
        {
            get
            {
                return this.endOurField;
            }
            set
            {
                this.endOurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ErrId
        {
            get
            {
                return this.errIdField;
            }
            set
            {
                this.errIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ErrorString
        {
            get
            {
                return this.errorStringField;
            }
            set
            {
                this.errorStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Park_Out
    {
        
        private long cityIdField;
        
        private long parkIdField;
        
        private string parkNameField;
        
        private bool onlineField;
        
        private string accNoField;
        
        private string serviceTaxNoField;
        
        private int errIdField;
        
        private string errorStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CityId
        {
            get
            {
                return this.cityIdField;
            }
            set
            {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ParkId
        {
            get
            {
                return this.parkIdField;
            }
            set
            {
                this.parkIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ParkName
        {
            get
            {
                return this.parkNameField;
            }
            set
            {
                this.parkNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Online
        {
            get
            {
                return this.onlineField;
            }
            set
            {
                this.onlineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AccNo
        {
            get
            {
                return this.accNoField;
            }
            set
            {
                this.accNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ServiceTaxNo
        {
            get
            {
                return this.serviceTaxNoField;
            }
            set
            {
                this.serviceTaxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ErrId
        {
            get
            {
                return this.errIdField;
            }
            set
            {
                this.errIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ErrorString
        {
            get
            {
                return this.errorStringField;
            }
            set
            {
                this.errorStringField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface TicketBookSoapChannel : KidzaniaService.TicketBookSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class TicketBookSoapClient : System.ServiceModel.ClientBase<KidzaniaService.TicketBookSoap>, KidzaniaService.TicketBookSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TicketBookSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TicketBookSoapClient.GetBindingForEndpoint(endpointConfiguration), TicketBookSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketBookSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TicketBookSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketBookSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TicketBookSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TicketBookSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.City_Out[]> FnSchedule_CityAsync(long CityId)
        {
            return base.Channel.FnSchedule_CityAsync(CityId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Park_Out[]> FnSchedule_ParkAsync(long CityId, long ParkId)
        {
            return base.Channel.FnSchedule_ParkAsync(CityId, ParkId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Park_Out[]> FnSchedule_Park_SyncAsync()
        {
            return base.Channel.FnSchedule_Park_SyncAsync();
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Shift_Out[]> FnSchedule_ShiftAsync(long CityId, long ParkId, System.DateTime Visit_Date, string PartnerId, string PartnerPwd)
        {
            return base.Channel.FnSchedule_ShiftAsync(CityId, ParkId, Visit_Date, PartnerId, PartnerPwd);
        }
        
        public System.Threading.Tasks.Task<bool> FnSchedule_Visitors_SyncAsync(long ParkId)
        {
            return base.Channel.FnSchedule_Visitors_SyncAsync(ParkId);
        }
        
        public System.Threading.Tasks.Task<bool> FnSchedule_Shift_SyncAsync(long ParkId, System.DateTime Visit_From, System.DateTime Visit_To)
        {
            return base.Channel.FnSchedule_Shift_SyncAsync(ParkId, Visit_From, Visit_To);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Sexes_Out[]> FnSchedule_SexesAsync(long ParkId)
        {
            return base.Channel.FnSchedule_SexesAsync(ParkId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vd_Park_Out[]> FnSchedule_VisitDate_ParkAsync(long ParkId, System.DateTime Visit_Date, string PartnerId, string PartnerPwd)
        {
            return base.Channel.FnSchedule_VisitDate_ParkAsync(ParkId, Visit_Date, PartnerId, PartnerPwd);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vd_Park_Out[]> FnSchedule_VisitDate_CityAsync(long CityId, System.DateTime Visit_Date, string PartnerId, string PartnerPwd)
        {
            return base.Channel.FnSchedule_VisitDate_CityAsync(CityId, Visit_Date, PartnerId, PartnerPwd);
        }
        
        public System.Threading.Tasks.Task<string> CancelBookAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId)
        {
            return base.Channel.CancelBookAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Book_Out> BookAsync(
                    long ParkId, 
                    long ShiftId, 
                    System.DateTime Visit_Date, 
                    long NoOfTickets, 
                    long VisitorId1, 
                    string VisitorTypeDesc1, 
                    string VisitorName1, 
                    string VisitorSex1, 
                    long VisitorAge1, 
                    long VisitorId2, 
                    string VisitorTypeDesc2, 
                    string VisitorName2, 
                    string VisitorSex2, 
                    long VisitorAge2, 
                    long VisitorId3, 
                    string VisitorTypeDesc3, 
                    string VisitorName3, 
                    string VisitorSex3, 
                    long VisitorAge3, 
                    long VisitorId4, 
                    string VisitorTypeDesc4, 
                    string VisitorName4, 
                    string VisitorSex4, 
                    long VisitorAge4, 
                    long VisitorId5, 
                    string VisitorTypeDesc5, 
                    string VisitorName5, 
                    string VisitorSex5, 
                    long VisitorAge5, 
                    long VisitorId6, 
                    string VisitorTypeDesc6, 
                    string VisitorName6, 
                    string VisitorSex6, 
                    long VisitorAge6, 
                    long VisitorId7, 
                    string VisitorTypeDesc7, 
                    string VisitorName7, 
                    string VisitorSex7, 
                    long VisitorAge7, 
                    long VisitorId8, 
                    string VisitorTypeDesc8, 
                    string VisitorName8, 
                    string VisitorSex8, 
                    long VisitorAge8, 
                    long VisitorId9, 
                    string VisitorTypeDesc9, 
                    string VisitorName9, 
                    string VisitorSex9, 
                    long VisitorAge9, 
                    long VisitorId10, 
                    string VisitorTypeDesc10, 
                    string VisitorName10, 
                    string VisitorSex10, 
                    long VisitorAge10, 
                    string PartnerId, 
                    string PartnerPwd, 
                    long UniqueRequestId, 
                    string CustomerIP)
        {
            return base.Channel.BookAsync(ParkId, ShiftId, Visit_Date, NoOfTickets, VisitorId1, VisitorTypeDesc1, VisitorName1, VisitorSex1, VisitorAge1, VisitorId2, VisitorTypeDesc2, VisitorName2, VisitorSex2, VisitorAge2, VisitorId3, VisitorTypeDesc3, VisitorName3, VisitorSex3, VisitorAge3, VisitorId4, VisitorTypeDesc4, VisitorName4, VisitorSex4, VisitorAge4, VisitorId5, VisitorTypeDesc5, VisitorName5, VisitorSex5, VisitorAge5, VisitorId6, VisitorTypeDesc6, VisitorName6, VisitorSex6, VisitorAge6, VisitorId7, VisitorTypeDesc7, VisitorName7, VisitorSex7, VisitorAge7, VisitorId8, VisitorTypeDesc8, VisitorName8, VisitorSex8, VisitorAge8, VisitorId9, VisitorTypeDesc9, VisitorName9, VisitorSex9, VisitorAge9, VisitorId10, VisitorTypeDesc10, VisitorName10, VisitorSex10, VisitorAge10, PartnerId, PartnerPwd, UniqueRequestId, CustomerIP);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> VouchersAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId)
        {
            return base.Channel.VouchersAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.AvailableVouchers_Out> AvailableVouchersAsync(string PartnerId, string PartnerPwd)
        {
            return base.Channel.AvailableVouchersAsync(PartnerId, PartnerPwd);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.UseVoucher_Out> UseVoucherAsync(
                    long ParkId, 
                    string PartnerId, 
                    string PartnerPwd, 
                    long UniqueRequestId, 
                    string BinNo, 
                    string CardName, 
                    int BookletId, 
                    long BookletNo, 
                    int VouId1, 
                    string VouNo1, 
                    string AddnlSecValidOnValue1, 
                    int VouId2, 
                    string VouNo2, 
                    string AddnlSecValidOnValue2, 
                    int VouId3, 
                    string VouNo3, 
                    string AddnlSecValidOnValue3, 
                    int VouId4, 
                    string VouNo4, 
                    string AddnlSecValidOnValue4, 
                    int VouId5, 
                    string VouNo5, 
                    string AddnlSecValidOnValue5, 
                    int VouId6, 
                    string VouNo6, 
                    string AddnlSecValidOnValue6, 
                    int VouId7, 
                    string VouNo7, 
                    string AddnlSecValidOnValue7, 
                    int VouId8, 
                    string VouNo8, 
                    string AddnlSecValidOnValue8, 
                    int VouId9, 
                    string VouNo9, 
                    string AddnlSecValidOnValue9, 
                    int VouId10, 
                    string VouNo10, 
                    string AddnlSecValidOnValue10, 
                    bool RepeatCall)
        {
            return base.Channel.UseVoucherAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, BinNo, CardName, BookletId, BookletNo, VouId1, VouNo1, AddnlSecValidOnValue1, VouId2, VouNo2, AddnlSecValidOnValue2, VouId3, VouNo3, AddnlSecValidOnValue3, VouId4, VouNo4, AddnlSecValidOnValue4, VouId5, VouNo5, AddnlSecValidOnValue5, VouId6, VouNo6, AddnlSecValidOnValue6, VouId7, VouNo7, AddnlSecValidOnValue7, VouId8, VouNo8, AddnlSecValidOnValue8, VouId9, VouNo9, AddnlSecValidOnValue9, VouId10, VouNo10, AddnlSecValidOnValue10, RepeatCall);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> AutoVouchersAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId)
        {
            return base.Channel.AutoVouchersAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.UseVoucher_Out> UseAutoVoucherAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId)
        {
            return base.Channel.UseAutoVoucherAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, VouId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.UseVoucher_Out> UseVoucherRollbackAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, bool IsRollbackAll, int VouId, string VouNo)
        {
            return base.Channel.UseVoucherRollbackAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, IsRollbackAll, VouId, VouNo);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Buy_Out> BuyAsync(
                    long ParkId, 
                    string PartnerId, 
                    string PartnerPwd, 
                    long UniqueRequestId, 
                    string PayType, 
                    string PayConfNo, 
                    string Remarks, 
                    string MobileNo, 
                    System.DateTime Visit_Date, 
                    long Shift_Id, 
                    string OrderId, 
                    string OrderRef, 
                    string MTR, 
                    string TransactionId, 
                    string RRN, 
                    string PayAuthId)
        {
            return base.Channel.BuyAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, PayType, PayConfNo, Remarks, MobileNo, Visit_Date, Shift_Id, OrderId, OrderRef, MTR, TransactionId, RRN, PayAuthId);
        }
        
        public System.Threading.Tasks.Task<bool> FnSchedule_Discount_SyncAsync(long ParkId, System.DateTime Visit_From, System.DateTime Visit_To)
        {
            return base.Channel.FnSchedule_Discount_SyncAsync(ParkId, Visit_From, Visit_To);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> IssueVouchersAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId)
        {
            return base.Channel.IssueVouchersAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> IssueVoucherValidateAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId, int IssueQty, string BinNo, string CardNo, string MobileNo, string EmailId, string UniqueCode)
        {
            return base.Channel.IssueVoucherValidateAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, VouId, IssueQty, BinNo, CardNo, MobileNo, EmailId, UniqueCode);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.IssueVouchers_Out> IssueVoucherBookAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId, int IssueQty, string BinNo, string CardNo, string MobileNo, string EmailId, string UniqueCode, string NameOnCard)
        {
            return base.Channel.IssueVoucherBookAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, VouId, IssueQty, BinNo, CardNo, MobileNo, EmailId, UniqueCode, NameOnCard);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.Vouchers_Out> IssueVoucherCancelAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId)
        {
            return base.Channel.IssueVoucherCancelAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId);
        }
        
        public System.Threading.Tasks.Task<KidzaniaService.IssueVouchers_Out> IssueVoucherMarkAsync(long ParkId, string PartnerId, string PartnerPwd, long UniqueRequestId, int VouId, int IssueQty, string BinNo, string CardNo, string MobileNo, string EmailId, string UniqueCode, string NameOnCard, string[] VouNos)
        {
            return base.Channel.IssueVoucherMarkAsync(ParkId, PartnerId, PartnerPwd, UniqueRequestId, VouId, IssueQty, BinNo, CardNo, MobileNo, EmailId, UniqueCode, NameOnCard, VouNos);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TicketBookSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TicketBookSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TicketBookSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://49.248.118.77/Kidzania_Service_Prod_Beta/Ticketbook.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TicketBookSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://49.248.118.77/Kidzania_Service_Prod_Beta/Ticketbook.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TicketBookSoap,
            
            TicketBookSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
