using FIL.Database.Migration.Core.Attributes;
using FIL.Database.Migration.Core.Migrators;

namespace FIL.Database.Migration.Migrators.Migrator_20171012133000_Transaction
{
    [Migration(2017, 10, 12, 13, 30, 0)]
    public class Migrator : BaseMigrator
    {
        public override void Up()
        {
            Create.Table("IPDetails")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("IPAddress").AsString(20)
                .WithColumn("CountryCode").AsString(20).Nullable()
                .WithColumn("CountryName").AsString(20).Nullable()
                .WithColumn("RegionCode").AsString(20).Nullable()
                .WithColumn("RegionName").AsString(20).Nullable()
                .WithColumn("City").AsString(20).Nullable()
                .WithColumn("Zipcode").AsString(20).Nullable()
                .WithColumn("TimeZone").AsString(20).Nullable()
                .WithColumn("Latitude").AsDecimal().Nullable()
                .WithColumn("Longitude").AsDecimal().Nullable()
                .WithColumn("MetroCode").AsString(20).Nullable()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("CardDetails")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("CardNumber").AsString(20)
                .WithColumn("CardTypeId").AsInt16().ForeignKey("CardTypes", "Id").Nullable()
                .WithColumn("FirstSix").AsString(20).Nullable()
                .WithColumn("Brand").AsString(20).Nullable()
                .WithColumn("SubBrand").AsString(20).Nullable()
                .WithColumn("CountryCode").AsString(10).Nullable()
                .WithColumn("CountryName").AsString(20).Nullable()
                .WithColumn("Bank").AsString(20).Nullable()
                .WithColumn("Type").AsString(20).Nullable()
                .WithColumn("Category").AsString(20).Nullable()
                .WithColumn("Latitude").AsDecimal().Nullable()
                .WithColumn("Longitude").AsDecimal().Nullable()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("Transactions")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("ChannelId").AsInt16().ForeignKey("Channels", "Id")
                .WithColumn("CurrencyId").AsInt32().ForeignKey("CurrencyTypes", "Id")
                .WithColumn("TotalTickets").AsInt16().Nullable()
                .WithColumn("GrossTicketAmount").AsDecimal().Nullable()
                .WithColumn("DeliveryCharges").AsDecimal().Nullable()
                .WithColumn("ConvenienceCharges").AsDecimal().Nullable()
                .WithColumn("ServiceCharge").AsDecimal().Nullable()
                .WithColumn("DiscountAmount").AsDecimal().Nullable()
                .WithColumn("NetTicketAmount").AsDecimal().Nullable()
                .WithColumn("DiscountCode").AsString(20).Nullable()
                .WithColumn("TransactionStatusId").AsInt16().ForeignKey("TransactionStatuses", "Id").Nullable()
                .WithColumn("IPDetailId").AsInt32().ForeignKey("IPDetails", "Id").Nullable()
                .WithColumn("IsEmailSend").AsBoolean().Nullable()
                .WithColumn("IsSmsSend").AsBoolean().Nullable()
                .WithColumn("OTP").AsInt16().Nullable().Nullable()
                .WithColumn("IsOTPVerified").AsBoolean().Nullable()
                .WithColumn("FirstName").AsString(20).Nullable()
                .WithColumn("LastName").AsString(20).Nullable()
                .WithColumn("PhoneCode").AsString(10).Nullable()
                .WithColumn("PhoneNumber").AsString(20).Nullable()
                .WithColumn("EmailId").AsString(128).Nullable()
                .WithColumn("CountryName").AsString(20).Nullable()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("TransactionDetails")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("TransactionId").AsInt64().ForeignKey("Transactions", "Id")
                .WithColumn("EventTicketAttributeId").AsInt64().ForeignKey("EventTicketAttributes", "Id")
                .WithColumn("TotalTickets").AsInt16()
                .WithColumn("PricePerTicket").AsDecimal()
                .WithColumn("DeliveryCharges").AsDecimal().Nullable()
                .WithColumn("ConvenienceCharges").AsDecimal().Nullable()
                .WithColumn("ServiceCharge").AsDecimal().Nullable()
                .WithColumn("DiscountAmount").AsDecimal().Nullable()
                .WithColumn("TicketTypeId").AsInt16().ForeignKey("TicketTypes", "Id").Nullable()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("TransactionDeliveryDetails")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("TransactionDetailId").AsInt64().ForeignKey("TransactionDetails", "Id")
                .WithColumn("DeliveryTypeId").AsInt16().ForeignKey("DeliveryTypes", "Id")
                .WithColumn("PickupBy").AsInt16().Nullable()
                .WithColumn("SecondaryName").AsString(20).Nullable()
                .WithColumn("SecondaryContact").AsString(20).Nullable()
                .WithColumn("SecondaryEmail").AsString(128).Nullable()
                .WithColumn("CourierAddress").AsString(20).Nullable()
                .WithColumn("CourierZipcode").AsInt32().ForeignKey("Zipcodes", "Id").Nullable()
                .WithColumn("DeliveryStatus").AsBoolean().Nullable()
                .WithColumn("DeliveryDate").AsDateTime().Nullable()
                .WithColumn("DeliverdTo").AsString(20).Nullable()
                .WithColumn("CourierServiceId").AsInt16().ForeignKey("CourierServices", "Id").Nullable()
                .WithColumn("TrackingId").AsString(20).Nullable()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();
        }
    }
}
