using FIL.Database.Migration.Core.Attributes;
using FIL.Database.Migration.Core.Migrators;

namespace FIL.Database.Migration.Migrators.Migrator_20180404160000_Integrations_ExOz
{
    [Migration(2018, 04, 04, 16, 0, 0)]
    public class Migrator : BaseMigrator
    {
        public override void Up()
        {
            Create.Table("ExOzCountries")
                .WithColumn("Id").AsInt32().PrimaryKey().Identity()
                .WithColumn("Name").AsString(40)
                .WithColumn("CountryMapId").AsInt32().ForeignKey("Countries", "Id")
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzStates")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("StateId").AsInt32()
               .WithColumn("Name").AsString(40)
               .WithColumn("UrlSegment").AsString(100)
               .WithColumn("CountryId").AsInt32().ForeignKey("ExOzCountries", "Id").Nullable()
               .WithColumn("StateMapId").AsInt32().ForeignKey("States", "Id").Nullable()
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();


            Create.Table("ExOzRegions")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("RegionId").AsInt32()
               .WithColumn("Name").AsString(100)
               .WithColumn("UrlSegment").AsString(100)
               .WithColumn("StateId").AsInt32().ForeignKey("ExOzStates", "Id")
               .WithColumn("OperatorQty").AsInt32().Nullable()
               .WithColumn("Offset").AsInt32().Nullable()
               .WithColumn("TimeStamp").AsString(40).Nullable()
               .WithColumn("OperatorCount").AsInt32().Nullable()
               .WithColumn("CategoryCount").AsInt32().Nullable()
               .WithColumn("CityId").AsInt32().ForeignKey("Cities", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();


            Create.Table("ExOzCategories")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("CategoryId").AsInt32()
               .WithColumn("RegionId").AsInt32().ForeignKey("ExOzRegions", "Id")
               .WithColumn("Name").AsString(40)
               .WithColumn("UrlSegment").AsString(100)
               .WithColumn("OperatorQty").AsInt32().Nullable()
               .WithColumn("Offset").AsInt32().Nullable()
               .WithColumn("TimeStamp").AsString(40).Nullable()
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzOperators")
              .WithColumn("Id").AsInt64().PrimaryKey().Identity()
              .WithColumn("OperatorId").AsInt64()
              .WithColumn("Name").AsString(200)
              .WithColumn("PublicName").AsString(200).Nullable()
              .WithColumn("UrlSegment").AsString(200)
              .WithColumn("CanonicalRegionUrlSegment").AsString(100)
              .WithColumn("RegionId").AsInt64()
              .WithColumn("EventId").AsInt64().ForeignKey("Events", "Id").Nullable()
              .WithColumn("VenueId").AsInt32().ForeignKey("Venues", "Id").Nullable()
              .WithColumn("Title").AsString(100).Nullable()
              .WithColumn("Description").AsString(int.MaxValue).Nullable()
              .WithColumn("Summary").AsString(int.MaxValue).Nullable()
              .WithColumn("Tips").AsString(int.MaxValue).Nullable()
              .WithColumn("Address").AsString(int.MaxValue).Nullable()
              .WithColumn("Phone").AsString(20).Nullable()
              .WithColumn("Rating").AsString(5).Nullable()
              .WithColumn("Quantity").AsInt32().Nullable()
              .WithColumn("Timestamp").AsString(100).Nullable()
              .WithColumn("GeoLocationName").AsString(200).Nullable()
              .WithColumn("Latitude").AsString(50).Nullable()
              .WithColumn("Longitude").AsString(50).Nullable()
              .WithColumn("IsEnabled").AsBoolean()
              .WithColumn("CreatedUtc").AsDateTime()
              .WithColumn("UpdatedUtc").AsDateTime().Nullable()
              .WithColumn("CreatedBy").AsGuid()
              .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzOperatorImages")
              .WithColumn("Id").AsInt64().PrimaryKey().Identity()
              .WithColumn("OperatorId").AsInt64().ForeignKey("ExOzOperators", "Id").Nullable()
              .WithColumn("ImageURL").AsString(int.MaxValue)
              .WithColumn("ImageType").AsString(20).Nullable()
              .WithColumn("IsEnabled").AsBoolean()
              .WithColumn("CreatedUtc").AsDateTime()
              .WithColumn("UpdatedUtc").AsDateTime().Nullable()
              .WithColumn("CreatedBy").AsGuid()
              .WithColumn("UpdatedBy").AsGuid().Nullable();


            Create.Table("ExOzProducts")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("ProductId").AsInt64()
                .WithColumn("Name").AsString(int.MaxValue)
                .WithColumn("UrlSegment").AsString(int.MaxValue)
                .WithColumn("Summary").AsString(int.MaxValue).Nullable()
                .WithColumn("OperatorId").AsInt64()
                .WithColumn("EventDetailId").AsInt64().ForeignKey("EventDetails", "Id")
                .WithColumn("VenueId").AsInt32().ForeignKey("Venues", "Id")
                .WithColumn("CanonicalRegionUrlSegment").AsString(int.MaxValue).Nullable()
                .WithColumn("BookingRequired").AsBoolean().Nullable()
                .WithColumn("HandlerKey").AsString(200).Nullable()
                .WithColumn("Title").AsString(int.MaxValue).Nullable()
                .WithColumn("Timestamp").AsString(200).Nullable()
                .WithColumn("Timezone").AsString(200).Nullable()
                .WithColumn("OperatorName").AsString(int.MaxValue).Nullable()
                .WithColumn("Description").AsString(int.MaxValue).Nullable()
                .WithColumn("MoreInfo").AsString(int.MaxValue).Nullable()
                .WithColumn("Tips").AsString(int.MaxValue).Nullable()
                .WithColumn("HelpCode").AsString(100).Nullable()
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzProductImages")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("ProductId").AsInt64().ForeignKey("ExOzProducts","Id")
                .WithColumn("EventDetailId").AsInt64().ForeignKey("EventDetails","Id")
                .WithColumn("ImageURL").AsString(200)
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzProductHighlights")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("ProductId").AsInt64().ForeignKey("ExOzProducts","Id")
                .WithColumn("EventDetailId").AsInt64().ForeignKey("EventDetails","Id")
                .WithColumn("Highlight").AsString(100)
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzProductSessions")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("ProductSessionId").AsInt64()
                .WithColumn("SessionName").AsString(200)
                .WithColumn("ProductId").AsInt64().ForeignKey("ExOzProducts","Id")
                .WithColumn("HasPickups").AsString(50)
                .WithColumn("Levy").AsDecimal()
                .WithColumn("IsExtra").AsBoolean()
                .WithColumn("TourHour").AsString(20).Nullable()
                .WithColumn("TourMinute").AsString(20).Nullable()
                .WithColumn("TourDuration").AsString(20).Nullable()
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();


            Create.Table("ExOzProductOptions")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("ProductOptionId").AsInt64()
                .WithColumn("Name").AsString(100)
                .WithColumn("Price").AsDecimal()
                .WithColumn("SessionId").AsInt64().Nullable()
                .WithColumn("EventTicketDetailId").AsInt64().ForeignKey("EventTicketDetails", "Id")
                .WithColumn("RetailPrice").AsDecimal().Nullable()
                .WithColumn("MaxQty").AsDecimal().Nullable()
                .WithColumn("MinQty").AsDecimal().Nullable()
                .WithColumn("DefaultQty").AsDecimal().Nullable()
                .WithColumn("Multiple").AsDecimal().Nullable()
                .WithColumn("Weight").AsDecimal().Nullable()
                .WithColumn("IsFromPrice").AsBoolean().Nullable()
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzPurchasers")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("UserId").AsInt64().ForeignKey("Users", "Id")
                .WithColumn("FirstName").AsString(20)
                .WithColumn("LastName").AsString(20)
                .WithColumn("Contact").AsString(20)
                .WithColumn("Email").AsString(30)
                .WithColumn("Country").AsString(20)
                .WithColumn("StateName").AsString(20)
                .WithColumn("Suburb").AsString(20)
                .WithColumn("Postcode").AsString(10)
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzTransactions")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("TransactionId").AsInt64().ForeignKey("Transactions","Id")
                .WithColumn("VoucherId").AsInt64()
                .WithColumn("PurchaserId").AsInt64().ForeignKey("ExOzPurchasers", "Id")
                .WithColumn("ReferenceNo").AsString(40)
                .WithColumn("ProductId").AsInt64()
                .WithColumn("SoldPrice").AsDecimal()
                .WithColumn("SoldPriceGST").AsDecimal()
                .WithColumn("AgentShare").AsDecimal()
                .WithColumn("AgentShareGST").AsDecimal()
                .WithColumn("VoucherDetailsId").AsInt64()
                .WithColumn("Notes").AsString(200)
                .WithColumn("PickupDetailsId").AsInt64()
                .WithColumn("DropOffDetailsId").AsInt64()
                .WithColumn("MetaData").AsString(100)
                .WithColumn("TicketLink").AsString(200)
                .WithColumn("IsCancelled").AsBoolean()
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzVoucherDetails")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("VoucherId").AsInt64()
                .WithColumn("TransactionId").AsInt64().ForeignKey("ExOzTransactions","Id")
                .WithColumn("Quantity").AsInt64()
                .WithColumn("ProductOption").AsInt64()
                .WithColumn("OptionName").AsString(20)
                .WithColumn("OptionUnitPrice").AsDecimal()
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzPickUps")
                .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                .WithColumn("PickupId").AsInt64()
                .WithColumn("Location").AsString(40)
                .WithColumn("Type").AsString(40)
                .WithColumn("PickupKey").AsInt64()
                .WithColumn("IsEnabled").AsBoolean()
                .WithColumn("CreatedUtc").AsDateTime()
                .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                .WithColumn("CreatedBy").AsGuid()
                .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("ExOzDropOffs")
                 .WithColumn("Id").AsInt64().PrimaryKey().Identity()
                 .WithColumn("DropOffId").AsInt64()
                 .WithColumn("Location").AsString(40)
                 .WithColumn("Type").AsString(40)
                 .WithColumn("IsEnabled").AsBoolean()
                 .WithColumn("CreatedUtc").AsDateTime()
                 .WithColumn("UpdatedUtc").AsDateTime().Nullable()
                 .WithColumn("CreatedBy").AsGuid()
                 .WithColumn("UpdatedBy").AsGuid().Nullable();
        }
    }
}
