using FIL.Database.Migration.Core.Attributes;
using FIL.Database.Migration.Core.Migrators;

namespace FIL.Database.Migration.Migrators.Migrator_20171013100000_VenueCreation
{
    [Migration(2017, 10, 13, 10, 0, 0)]
    public class Migrator : BaseMigrator
    {
        public override void Up()
        {
            Create.Table("EntryGates")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("Name").AsString(100)
               .WithColumn("StreetInformation").AsString(200).Nullable()
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MasterVenueLayouts")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("LayoutName").AsString(200)
               .WithColumn("VenueId").AsInt32().ForeignKey("Venues", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MasterVenueLayoutSections")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("SectionName").AsString(200)
               .WithColumn("MasterVenueLayoutId").AsInt32().ForeignKey("MasterVenueLayouts", "Id")
               .WithColumn("MasterVenueLayoutSectionId").AsInt32().Nullable()
               .WithColumn("Capacity").AsInt32()
               .WithColumn("EntryGateId").AsInt32().ForeignKey("EntryGates", "Id")
               .WithColumn("VenueLayoutAreaId").AsInt16().ForeignKey("VenueLayoutAreas", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MasterVenueLayoutSectionSeats")
               .WithColumn("Id").AsInt64().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("SeatTag").AsString(50)
               .WithColumn("MasterVenueLayoutSectionId").AsInt32().ForeignKey("MasterVenueLayoutSections", "Id")
               .WithColumn("RowNumber").AsString(50)
               .WithColumn("ColumnNumber").AsString(50)
               .WithColumn("RowOrder").AsInt32().Nullable()
               .WithColumn("ColumnOrder").AsInt32().Nullable()
               .WithColumn("SeatTypeId").AsInt16().ForeignKey("SeatTypes", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("TournamentLayouts")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("LayoutName").AsString(200)
               .WithColumn("EventId").AsInt64().ForeignKey("Events", "Id")
               .WithColumn("MasterVenueLayoutId").AsInt32().ForeignKey("MasterVenueLayouts", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("TournamentLayoutSections")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("SectionName").AsString(200)
               .WithColumn("MasterVenueLayoutSectionId").AsInt32().ForeignKey("MasterVenueLayoutSections", "Id").Nullable()
               .WithColumn("TournamentLayoutId").AsInt32().ForeignKey("TournamentLayouts", "Id")
               .WithColumn("TournamentLayoutSectionId").AsInt32().Nullable()
               .WithColumn("Capacity").AsInt32()
               .WithColumn("EntryGateId").AsInt32().ForeignKey("EntryGates", "Id")
               .WithColumn("VenueLayoutAreaId").AsInt16().ForeignKey("VenueLayoutAreas", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("TournamentLayoutSectionSeats")
               .WithColumn("Id").AsInt64().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("SeatTag").AsString(50)
               .WithColumn("TournamentLayoutSectionId").AsInt32().ForeignKey("TournamentLayoutSections", "Id")
               .WithColumn("RowNumber").AsString(50)
               .WithColumn("ColumnNumber").AsString(50)
               .WithColumn("RowOrder").AsInt32().Nullable()
               .WithColumn("ColumnOrder").AsInt32().Nullable()
               .WithColumn("SeatTypeId").AsInt16().ForeignKey("SeatTypes", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MatchLayouts")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("LayoutName").AsString(200)
               .WithColumn("EventDetailId").AsInt64().ForeignKey("EventDetails", "Id")
               .WithColumn("TournamentLayoutId").AsInt32().ForeignKey("TournamentLayouts", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MatchLayoutSections")
               .WithColumn("Id").AsInt32().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("SectionName").AsString(200)
               .WithColumn("TournamentLayoutSectionId").AsInt32().ForeignKey("TournamentLayoutSections", "Id").Nullable()
               .WithColumn("MatchLayoutId").AsInt32().ForeignKey("MatchLayouts", "Id")
               .WithColumn("MatchLayoutSectionId").AsInt32().Nullable()
               .WithColumn("Capacity").AsInt32()
               .WithColumn("EntryGateId").AsInt32().ForeignKey("EntryGates", "Id")
               .WithColumn("VenueLayoutAreaId").AsInt16().ForeignKey("VenueLayoutAreas", "Id")
               .WithColumn("TicketCategoryId").AsInt64().Nullable()
               .WithColumn("IsPrintBigX").AsBoolean().Nullable()
               .WithColumn("IsPrintSeatNumber").AsBoolean().Nullable()
               .WithColumn("StaircaseNumber").AsString(20).Nullable()
               .WithColumn("RampNumber").AsString(20).Nullable()
               .WithColumn("ScanGateName").AsString(20).Nullable()
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MatchLayoutSectionSeats")
               .WithColumn("Id").AsInt64().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("SeatTag").AsString(50)
               .WithColumn("MatchLayoutSectionId").AsInt32().ForeignKey("MatchLayoutSections", "Id")
               .WithColumn("RowNumber").AsString(50)
               .WithColumn("ColumnNumber").AsString(50)
               .WithColumn("RowOrder").AsInt32().Nullable()
               .WithColumn("ColumnOrder").AsInt32().Nullable()
               .WithColumn("SeatTypeId").AsInt16().ForeignKey("SeatTypes", "Id")
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();

            Create.Table("MatchSeatTicketDetails")
               .WithColumn("Id").AsInt64().PrimaryKey().Identity()
               .WithColumn("AltId").AsGuid()
               .WithColumn("MatchLayoutSectionSeatId").AsInt64().ForeignKey("MatchLayoutSectionSeats", "Id")
               .WithColumn("EventTicketDetailId").AsInt64().ForeignKey("EventTicketDetails", "Id")
               .WithColumn("Price").AsDecimal()
               .WithColumn("ChannelId").AsInt16().ForeignKey("Channels", "Id").Nullable()
               .WithColumn("SeatStatusId").AsInt16().ForeignKey("SeatStatuses", "Id")
               .WithColumn("BarcodeNumber").AsString(50).Nullable()
               .WithColumn("PrintStatusId").AsInt16().ForeignKey("PrintStatuses", "Id").Nullable()
               .WithColumn("PrintCount").AsInt32().Nullable()
               .WithColumn("PrintedBy").AsString(50).Nullable()
               .WithColumn("PrintDateTime").AsDateTime().Nullable()
               .WithColumn("EntryCount").AsInt32().Nullable()
               .WithColumn("EntryStatus").AsBoolean().Nullable()
               .WithColumn("EntryDateTime").AsDateTime().Nullable()
               .WithColumn("CheckedDateTime").AsDateTime().Nullable()
               .WithColumn("EntryCountAllowed").AsInt32().Nullable()
               .WithColumn("TicketTypeId").AsInt16().ForeignKey("TicketTypes", "Id")
               .WithColumn("IPDetailId").AsInt32().ForeignKey("IPDetails", "Id").Nullable()
               .WithColumn("IsEnabled").AsBoolean()
               .WithColumn("CreatedUtc").AsDateTime()
               .WithColumn("UpdatedUtc").AsDateTime().Nullable()
               .WithColumn("CreatedBy").AsGuid()
               .WithColumn("UpdatedBy").AsGuid().Nullable();
        }
    }
}
